# Site settings
title: ZFY Blog
SEOTitle: 张峰源的博客 | ZFY Blog
header-img: img/Miku-Stage.PNG
email: zhangfy1998@outlook.com
description: "I feel strongly that I can make it."
keyword: "ZFY, ZFY Blog, 张峰源的博客, zhangfengyuan, 张峰源, iOS, Andriod, 动漫, Animation"
url: "https://fy-zhang.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/FY-Zhang/FY-Zhang.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "That man is the richest whose pleasure are the cheapest."
sidebar-avatar: /img/Accelerator.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:
# zhihu_username:
github_username:     FY-Zhang
# facebook_username:
# jianshu_username:
# twitter_username:




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
disqus_username: fy_zhang

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 4ebd6cd16231871b034e                            #生成的clientID
  clientSecret: 91054d2d895b070fb83cccf6151a21553af9dd8e    #生成的clientSecret
  repo: FY-Zhang.github.io    #仓库名称
  owner: FY-Zhang    #github用户名
  admin: FY-Zhang
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 53a5a4bb423d025ccccc37486328a25c

# Google Analytics
# ga_track_id: 'UA-131420800-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
#friends: [
#    {
#        title: "WY",
#        href: "http://zhengwuyang.com"
#    },{
#        title: "简书·BY",
#        href: "http://www.jianshu.com/u/e71990ada2fd"
#    },{
#        title: "Apple",
#        href: "https://apple.com"
#    },{
#        title: "Apple Developer",
#        href: "https://developer.apple.com/"
#    }
#]
